[INFO:2023-05-03 10:00:05,327] Episode: 1 | Timesteps Played: 167 | Mean Loss: 0.000 | Mean Reward: 0.599 | Target Updates: 0
[INFO:2023-05-03 10:00:05,584] Episode: 2 | Timesteps Played: 207 | Mean Loss: 0.000 | Mean Reward: 0.773 | Target Updates: 0
Traceback (most recent call last):
  File "/Users/mt361/Desktop/RL-Bandits/train.py", line 61, in <module>
    algo.train()
  File "/Users/mt361/Desktop/RL-Bandits/algo.py", line 504, in train
    utils.validate(self.Q_network, self.args.render, nepisodes=5, wandb=wandb, mode='resize')
  File "/Users/mt361/Desktop/RL-Bandits/utils.py", line 77, in validate
    action, prev_state = model.get_action(observation, prev_state)
  File "/Users/mt361/Desktop/RL-Bandits/model.py", line 215, in get_action
    logits = self(x)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/mt361/Desktop/RL-Bandits/model.py", line 190, in forward
    X = F.relu(self.fc1(X))
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x784 and 3136x512)